---
# tasks file for homebrew
- name: Create ~/.config/homebrew
  file:
      path: "{{ local_home }}/.config/homebrew"
      state: directory

- name: download installation script
  get_url:
    url=https://raw.githubusercontent.com/Homebrew/install/master/install
    dest="{{ local_home }}/.config/homebrew/install"

- name: install Homebrew
  command: ruby "{{ local_home }}/.config/homebrew/install" creates=/usr/local/bin/brew

- name: update Homebrew
  homebrew: update_homebrew=yes

- name: tap bundle
  homebrew_tap: tap=homebrew/bundle state=present

- name: prepare Brewfile
  template:
      dest="{{ local_home }}/.config/homebrew/Brewfile"
      src=Brewfile
      mode=0644

- name: bundle
  command: brew bundle --file="{{ local_home }}/.config/homebrew/Brewfile"

- name: clean up old versions
  command: brew cleanup
