---
# tasks file for neovim
- name: Symlink nvim to dotfiles
  file:
    path=~/.config/nvim
    src={{ dotfiles_dir }}
    state=link
    force=yes

- name: Install plugins
  command: nvim +PlugInstall +qall
