# https://stackoverflow.com/a/42265848/3297680
export GPG_TTY=$(tty)

# man bash | grep -A1 '\-f file$'
#        -f file
#               True if file exists and is a regular file.
#        -r file
#               True if file exists and is readable.
import () {
    [[ -r "$1" ]] && source "$1"
}

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
import "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"

import $dotfiles_dir/shell/common.sh

import $HOME/.fzf.zsh
import $ASDF_DIR/asdf.sh
import "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/zshrc"

# searching through history with up and down arrows
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey "^[[A" up-line-or-beginning-search # Up
bindkey "^[[B" down-line-or-beginning-search # Down

# case insensitive auto completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# https://asdf-vm.com/guide/getting-started.html#_3-install-asdf
fpath=(${ASDF_DIR}/completions $fpath)

# https://unix.stackexchange.com/a/477909/178887
autoload -Uz compinit
compinit

import $dotfiles_dir/shell/zsh/powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
import $HOME/.p10k.zsh
import $HOME/.local_bashrc

source <(kubectl completion zsh)

# vim: set ft=sh ts=4 sw=4 et ai :
