alias ll='ls -lh'
alias la='ls -aAh'
alias l='ls -CF'
alias g="git status"
alias vim='nvim'
alias vi="vi -u NONE"
alias ctagsit="ctags --append=no --recurse --totals --exclude=blib --exclude=.svn --exclude=.get --exclude='@.gitignore' --extra=q"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# don't put duplicate lines or lines starting with space in the history.
# HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend

export TERM=xterm-256color
export LANG='en_US.UTF-8'
export EDITOR=nvim
export GIT_EDITOR="nvim"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T]: "

source $dotfiles_dir/git/git-completion.bash
source $dotfiles_dir/bash/bash-sensible/sensible.bash
# [[ $- = *i* ]] && source $dotfiles_dir/liquidprompt/liquidprompt

# GIT_PROMPT_ONLY_IN_REPO=1
GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status
GIT_PROMPT_IGNORE_SUBMODULES=1 # uncomment to avoid searching for changed files in submodules
GIT_PROMPT_SHOW_UNTRACKED_FILES=all # can be no, normal or all; determines counting of untracked files
source $dotfiles_dir/bash/bash-git-prompt/gitprompt.sh

# useful functions stolen from https://github.com/Bash-it/bash-it
function mkcd() {
    mkdir -p -- "$*"
    cd -- "$*"
}
# display all ip addresses for this host
function ips ()
{
    if command -v ifconfig &>/dev/null
    then
        ifconfig | awk '/inet /{ print $2 }'
    elif command -v ip &>/dev/null
    then
        ip addr | grep -oP 'inet \K[\d.]+'
    else
        echo "You don't have ifconfig or ip command installed!"
    fi
}
# search through directory contents with grep
function lsgrep ()
{
    ls | grep "$*"
}
# back up file with timestamp
function buf ()
{
    local filename=$1
    local filetime=$(date +%Y%m%d_%H%M%S)
    cp -a "${filename}" "${filename}_${filetime}"
}
# move files to hidden folder in /tmp/.trash
function del() {
    mkdir -p /tmp/.trash && mv "$@" /tmp/.trash;
}
